#Author: Chirag Jain (CJ)
#Deployment for Amazon website using 2 pods and nginx Image
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy: amazon
  name: amazon
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amazon
  template:
    metadata:
      labels:
        app: amazon
    spec:
      containers:
      - image: nginx:1.17.10
        name: amazon-website
