#Deployment for Flipkart website using 2 pods and nginx Image
#-----Default Namespace------- cjain------------
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    deploy: flipkart
  name: flipkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flipkart
  template:
    metadata:
      labels:
        app: flipkart
    spec:
      containers:
      - image: nginx:1.17.10
        name: flipkart-website
